### ISSUE TITLE
Issue at hstack

### ISSUE THREAD

**Issue by sumedha765** [sid-sr/ml-notebooks#1]
Sid,

I was trying to replicate your code but i am getting an error message 

ValueError: cannot copy sequence with size 10500 to array axis with dimension 1

at this line:
X = hstack(vals1)

Can you please crosscheck and help me in resolving this issue?
![Issue](https://user-images.githubusercontent.com/57921643/79101831-108db200-7d87-11ea-82b9-f5bdd58d481e.PNG)

**Comment by sid-sr** [comment]
Sorry for the minor error,
* I seem to have reversed the order of the lists to use for one hot encoding and cat boost encoding and this caused the problem with hstack. Here's the change: 
```
    # Transforming the data
    for i, enc in enumerate(encs_ohe):    # initially this was encs_cb
        enc_val.append(enc.transform(data[cat_cols[i]].values.reshape(-1, 1)))
    for i, enc in enumerate(encs_cb):     # and this was encs_ohe
        data[cat_cols[i]] = enc.transform(data[cat_cols[i]].values.reshape(-1, 1))    
```
* Also, I changed the one hot encoding variable name, and not update it elsewhere in the code, causing a NameError.

I've fixed both these errors now and updated the code.

**Comment by sumedha765** [comment]
Thanks. I am able to run it now.
